ALTER TABLE membros
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS escolaridade VARCHAR(100),
ADD COLUMN IF NOT EXISTS profissao VARCHAR(100),
ADD COLUMN IF NOT EXISTS data_filiacao DATE,
ADD COLUMN IF NOT EXISTS nome_pai VARCHAR(255),
ADD COLUMN IF NOT EXISTS nome_mae VARCHAR(255),
ADD COLUMN IF NOT EXISTS filhos TEXT,
ADD COLUMN IF NOT EXISTS has_membership_card BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS membership_card_issued_at DATE,
ADD COLUMN IF NOT EXISTS lgpd_finalidade TEXT,
ADD COLUMN IF NOT EXISTS lgpd_autorizacao_imagem BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lgpd_autorizacao_comunicacao BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS importacao_id VARCHAR(36) REFERENCES importacoes_log(id);
CREATE INDEX IF NOT EXISTS idx_membros_importacao_id ON membros(importacao_id);
